### PR TITLE
Fixed index.md handling

### PR DESCRIPTION
**Pull request by mtirionMSFT**
* INDEX.md files were ignored in handling. This is removed from the code to have proper handling.
* folders not containing sub-folders were parsed differently from folders with sub-folders. Corrected this behavior.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Looks good to me! Thanks for finding time to make this fix.

**Comment by mtirionMSFT** [comment]
@sacrejohn I removed it because in both cases WalkDirectoryTree is needed. But I overlooked the different parameters. Will bring that back. Thanks for your comment :)

**Comment by mtirion** [comment]
@sacrejohn issue fixed. WalkDirectoryTree is now done in both cases, but href determined as before.

**Comment by sacrejohn** [comment]
I have looked at and tested the new version. It seems to me that the **WalkDirectoryTree** method should only be called in the else clause, otherwise 1 child element is created. Exactly like the inital code.

**Pull request merged**
